# Generated by Django 4.2.1 on 2023-07-05 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0002_remove_hotel_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='HotelReservation.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 16, 52, 21, 919459)),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 16, 52, 21, 919459)),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='HotelReservation.hotel'),
        ),
    ]
