# Generated by Django 4.2.1 on 2023-07-05 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0004_alter_hotelbooking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, default='https://www.parsnaz.com/upload/1/0.183712001307464656_parsnaz_ir.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 19, 12, 9, 601477)),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 19, 12, 9, 601477)),
        ),
    ]
