# Generated by Django 4.2.1 on 2023-07-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0002_remove_hotel_capacity_and_more'),
        ('TrainBooking', '0002_alter_train_destination_alter_train_origin'),
        ('FlightBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='HotelReservation.city'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='HotelReservation.city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
