# Generated by Django 4.2.2 on 2023-06-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlightBooking', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='origin_airport',
        ),
    ]
