# Generated by Django 4.2.2 on 2023-06-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightBooking', '0003_remove_flight_origin_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightreservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
