# Generated by Django 4.2.2 on 2023-06-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightBooking', '0004_alter_flightreservation_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightreservation',
            name='num_adults',
            field=models.PositiveSmallIntegerField(verbose_name='number of adults'),
        ),
        migrations.AlterField(
            model_name='flightreservation',
            name='num_children',
            field=models.PositiveSmallIntegerField(verbose_name='number of kids'),
        ),
    ]
