# Generated by Django 4.2.1 on 2023-07-04 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FlightBooking', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('is_adult', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('train_number', models.CharField(max_length=10)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_arrival_city', to='FlightBooking.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_departure_city', to='FlightBooking.city')),
            ],
        ),
        migrations.CreateModel(
            name='TrainReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_round_trip', models.BooleanField(default=False)),
                ('num_adults', models.PositiveSmallIntegerField(verbose_name='number of adults')),
                ('num_children', models.PositiveSmallIntegerField(verbose_name='number of kids')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('passengers', models.ManyToManyField(to='TrainBooking.passenger')),
                ('return_train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_train_reservations', to='TrainBooking.train')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainBooking.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrainReservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
