# Generated by Django 4.2.1 on 2023-07-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelReservation', '0002_remove_hotel_capacity_and_more'),
        ('TrainBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_arrival_city', to='HotelReservation.city'),
        ),
        migrations.AlterField(
            model_name='train',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_departure_city', to='HotelReservation.city'),
        ),
    ]
